version: "2"

services:
  mysql:
    container_name: supercars-mysql
    build:
      context: "mysql"
      dockerfile: "Dockerfile"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "root"
    expose:
      - '3306'
    ports:
      - "3306:3306"
    networks:
      - app-net

  tomcat:
    container_name: "supercars-tomcat"
    build:
      context: "tomcat"
      dockerfile: "Dockerfile"
    environment:
      MYSQL_HOST: 'supercars-mysql'
      MYSQL_PORT: '3306'
    env_file:
      - appdynamics-env
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - app-net
    depends_on:
      - mysql

  loader:
    container_name: "supercars-loader"
    build:
      context: "loader"
      dockerfile: "Dockerfile"
    networks:
      - app-net
    depends_on:
      - tomcat

  dbagent:
    container_name: "supercar-dbagent"
    build:
      context: "dbagent"
      dockerfile: "Dockerfile"
    networks:
      - app-net
    env_file:
      - appdynamics-env
    depends_on:
      - mysql

  machineagent:
    container_name: "supercar-machineagent"
    build:
      context: "machineagent"
      dockerfile: "Dockerfile"
    env_file:
      - appdynamics-env

networks:
  app-net:
    driver: bridge

